all : part1 part2 part3 part4

part1 : part1.c
	gcc -g -o part1 part1.c

part2 : part2.c
	gcc -g -o part2 part2.c

part3 : part3.c
	gcc -g -o part3 part3.c

part4 : part4.c
	gcc -g -o part4 part4.c

clean:
	rm -rf part1
	rm -rf part2
	rm -rf part3
	rm -rf part4